---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-config
  namespace: traefik
data:
  legagy.toml: |
    [http.routers.legacy]
      rule = "Host(`DOMAIN`)"
      service = "legacy@file"
      entryPoints = ["websecure"]
      [http.routers.legacy.tls]
        certResolver = "myresolver"

    [http.services.legacy]
      [http.services.legacy.loadBalancer]
        passHostHeader = false
        [[http.services.legacy.loadBalancer.servers]]
          url = "https://gateway-api.sigs.k8s.io"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: traefik
          args:
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.websecure.http.tls=true
            - --providers.file.directory=/dynamic
            - --providers.file.watch=true
            - --providers.kubernetescrd.allowcrossnamespace
            - --experimental.kubernetesgateway=true
            - --providers.kubernetesgateway=true
            - --providers.kubernetesingress.ingressclass=traefik-lb
            - --api.dashboard
            - --metrics.prometheus
            - --log.level=debug
            - --certificatesresolvers.myresolver.acme.tlschallenge
            - --certificatesresolvers.myresolver.acme.email=michael@traefik.io
            - --certificatesresolvers.myresolver.acme.storage=acme.json
            # # Please note that this is the staging Let's Encrypt server.
            # # Once you get things working, you should remove that whole line altogether.
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: metrics
              containerPort: 8080
          volumeMounts:
            - name: dynamicconfig
              mountPath: /dynamic
      volumes:
        - name: dynamicconfig
          configMap:
            name: dynamic-config
